# To get started with security, check out the documentation:
# http://symfony.com/doc/current/security.html
security:
    encoders:
        AppBundle\Entity\Users: bcrypt

    providers:
        administrators:
            entity: { class: AppBundle:Users, property: name }
        api_key_user_provider:
            id: api_key_user_provider

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPERADMIN: ROLE_ADMIN



    # providers:
    #     in_memory:
    #         memory:
    #             users:
    #                 user:
    #                     password: user1
    #                     roles: 'ROLE_USER'
    #                 admin:
    #                     password: admin1
    #                     roles: 'ROLE_ADMIN'


    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        admin_area:
            pattern:    ^/admin
            http_basic:
                realm: "My admin area"
        api_area:
            pattern: ^/api
            stateless: true
            simple_preauth:
                authenticator: apikey_authenticator
            provider: api_key_user_provider


#         main:
#             pattern: ^/
#             anonymous: ~
#             http_basic: ~

    access_control:
        - { path: ^/admin, roles: ROLE_SUPERADMIN }
        - { path: ^/, role: IS_AUTHENTICATED_ANONYMOUSLY }




