# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]


    apikey_authenticator:
        class: AppBundle\Security\ApiKeyAuthenticator
        arguments: [ "@doctrine.orm.entity_manager" ]

    api_key_user_provider:
        class: AppBundle\Security\ApiKeyUserProvider
        arguments: [ "@doctrine.orm.entity_manager" ]

    logout_listener:
        class: AppBundle\Security\LogoutListener
        arguments: [ "@security.http_utils", "@security.token_storage" ]
            
    kernel.listener.exceptions:
        class: AppBundle\EventListener\ExceptionListener
        tags:
           - { name: kernel.event_listener, event: kernel.exception }
            
